[package]
name = "i3title-rs"
version = "0.1.0"
authors = ["Kacper Wardega <kacper@wardega.com>"]
edition = "2018"
license = "Apache 2.0"
license-file = "LICENSE"

[dependencies]
i3ipc = "0.10.1"
clap = "3.0.0-beta.2"
